# API Keys
GOOGLE_API_KEY = "AIzaSyBlItDdGyXvmtkJK9MpKcz_QZjaZmjVnkE"  
OPENAI_API_KEY = "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"  # Replace with your actual OpenAI API key

# Other App Secrets
app_name = "PeopleRadar" 